
version: '3'

services:
  token-server:
    image: cinob/alitoken-server:latest
    restart: always
    container_name: token-server
    environment:
      RUST_LOG: "info"
    ports:
      - "8080:8080"